name = "cloud-mail"
main = "src/index.js"
compatibility_date = "2025-06-04"
keep_vars = true
workers_dev = false
preview_urls = false

[observability]
enabled = true

# 中间数据库、KV、R2、AI、assets配置不动

[assets]
binding = "assets"
directory = "./dist"
not_found_handling = "single-page-application"
run_worker_first = true

# 注释定时，避开cron限额报错
# [triggers]
# crons = ["0 16 * * *"]

[vars]
# 环境变量保留你原有注释

[build]
command = "pnpm --prefix ../mail-vue install && pnpm --prefix ../mail-vue run build"
